[WIP] allow to specify boot volume size in OCI builder
hashicorp/packer pull request #10017
Opened 2020-09-30 11:04 UTC by kostasns

Currently `oci` builder will use default size (46 Gb) for boot volume and consequently the resulting image.
If a larger default boot volume is required, what we do is manually re-create an image by launching an instance with larger disk size.

This MR allows to pass in a boot volume size in the template creating an image with desired default disk size after the build.
Introduced a new optional variable `boot_volume_size_in_gbs` with Default set to 50 GBs.

Closes #7117

2020-09-30 11:04 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10017)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10017)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Kostas** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10017).</sub>

2020-09-30 22:46 UTC, SwampDragons requested changes
Overall this looks like a straightforward change. My only nitpick is that in other builders, we tend to use the term "disk_size" for this feature, and I think it would be nice to keep it standard across builders. Since the underlying feature name is BootVolumeSizeInGBs in the API, you can document it with a doc string something along these lines:

`disk_size (int64) - The size of the disk in GB. This defaults to 50, which is 50GB. This sets the BootVolumeSizeInGBs option when launching the instance`

over in https://github.com/hashicorp/packer/blob/72166febee89db489655938a047500a4569c6b3e/website/pages/docs/builders/oracle/oci.mdx

2020-10-01 06:04 UTC, kostasns commented
Hi, thank you for the suggestions :)

2020-10-02 18:03 UTC, SwampDragons approved these changes

2020-10-02 18:04 UTC, SwampDragons commented
Awesome, thanks!!

2020-10-02 18:04 UTC, merged

2020-10-02 20:08 UTC, kostasns commented
Great! Thank you :) Being golang beginner - this made my day ;)