[WIP] Azure: arm builder: adding keep_os_disk parameter to control OS disk deletion
hashicorp/packer pull request #10045
Opened 2020-10-05 19:26 UTC by ContigoRed

Added a new `keep_os_disk` parameter to azure arm builder.
If `keep_os_disk` is set, the OS disk is not deleted. The default is `false`, as currently packer deletes the OS disk by default.

Closes #6752

2020-10-05 19:26 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10045)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10045)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10045).</sub>

2020-10-05 21:54 UTC, SwampDragons commented
Hi, thanks for opening this. 

It looks like this code will skip deleting the disk, but it doesn't add the disk to the artifact which feels like an oversight if the point is for the user to be able to access this disk in the future. I'd love a look from @paulmey or one of our other friends over at Microsoft.

2020-10-06 06:00 UTC, ContigoRed commented
> Hi, thanks for opening this.
> 
> It looks like this code will skip deleting the disk, but it doesn't add the disk to the artifact which feels like an oversight if the point is for the user to be able to access this disk in the future. I'd love a look from @paulmey or one of our other friends over at Microsoft.

Hi
thanks for replying.

I see `OSDiskUri` and `OSDiskUriReadOnlySas` fields in the artifact created in func `NewArtifact` in file builder/azure/arm/artifact.go.

Is there anything else should be added there?

2020-10-06 22:37 UTC, SwampDragons commented
I think those are correct and sufficient.

2020-11-23 18:51 UTC, ContigoRed commented
hi
what are we waiting for?

2020-11-30 18:57 UTC, SwampDragons commented
I answered your question 
> Is there anything else should be added there? 

And expected to see more commits come through afterwards; I assumed you still had more work you were doing on this 😬 

Are you ready to get a review? I can fix conflicts for you since I suspect most of them are due to a recent refactor I did.

2020-12-03 16:36 UTC, ContigoRed commented
> I answered your question
> 
> > Is there anything else should be added there?
> 
> And expected to see more commits come through afterwards; I assumed you still had more work you were doing on this 
> 
> Are you ready to get a review? I can fix conflicts for you since I suspect most of them are due to a recent refactor I did.

yes, thanks

2020-12-07 17:48 UTC, SwampDragons commented
Okay, I'll try to get that review done this week.

2020-12-18 01:01 UTC, SwampDragons requested changes
Okay, I looked this over again. Thanks for your patience. 

In my initial review, I pointed out that you aren't setting the disk URI in the artifact. You followed up asking about the field in the artifact interface: `OSDiskUri`

I think I was unclear in my reply. What I meant to say was, "yes, that's the right field, please set that field for managed image artifacts". But I think what you got from my too-short reply was "yeah, that's already set, I guess you don't need to do anything". 

When you said there was no more work to do I assumed you'd checked that the artifact had the necessary files, and it took me a while to come back and take a closer look. 

Currently in this PR, the OSDiskUri field is not being set by the function that actually creates the managed image artifacts: https://github.com/hashicorp/packer/blob/dd9a8b2669138fba23d26c193d5ef8495d7ff5f7/builder/azure/arm/artifact.go#L49

I tested today and was able to confirm that while the code in this PR successfully prevents deleting the OS disk, the output doesn't say anything about a disk, and navigating to the Azure ui portal it's also unclear which disk is associated with the managed image in question. The only way to get the disk would be to parse Packer's verbose logs.  

I think this PR isn't complete until the os disk uri is printed to the artifact. You can probably take a look at how the vhdURI is being found for vhd builds for an idea of how to accomplish this: https://github.com/hashicorp/packer/blob/dd9a8b2669138fba23d26c193d5ef8495d7ff5f7/builder/azure/arm/artifact.go#L85

2021-02-18 10:44 UTC, sylviamoss commented
Hello @ContigoRed, are you still planning to work on this?

2021-03-01 19:24 UTC, ContigoRed commented
> Okay, I looked this over again. Thanks for your patience.
> 
> In my initial review, I pointed out that you aren't setting the disk URI in the artifact. You followed up asking about the field in the artifact interface: `OSDiskUri`
> 
> I think I was unclear in my reply. What I meant to say was, "yes, that's the right field, please set that field for managed image artifacts". But I think what you got from my too-short reply was "yeah, that's already set, I guess you don't need to do anything".
> 
> When you said there was no more work to do I assumed you'd checked that the artifact had the necessary files, and it took me a while to come back and take a closer look.
> 
> Currently in this PR, the OSDiskUri field is not being set by the function that actually creates the managed image artifacts:
> 
> https://github.com/hashicorp/packer/blob/dd9a8b2669138fba23d26c193d5ef8495d7ff5f7/builder/azure/arm/artifact.go#L49
> 
> I tested today and was able to confirm that while the code in this PR successfully prevents deleting the OS disk, the output doesn't say anything about a disk, and navigating to the Azure ui portal it's also unclear which disk is associated with the managed image in question. The only way to get the disk would be to parse Packer's verbose logs.
> 
> I think this PR isn't complete until the os disk uri is printed to the artifact. You can probably take a look at how the vhdURI is being found for vhd builds for an idea of how to accomplish this:
> 
> https://github.com/hashicorp/packer/blob/dd9a8b2669138fba23d26c193d5ef8495d7ff5f7/builder/azure/arm/artifact.go#L85

added the os dist to the artifact, and tests to that.

need to rebase all that on master and squash all the commits into one at the end.

not sure what's that "Vercel" thing.

2021-03-22 14:27 UTC, nywilken commented
Hey @ContigoRed thanks for keeping this change updated. There was a recent refactor to the logic for deleting the os disk, needed to fix a regression ,which is causing a conflict and may change the implementation a bit. Can you please rebase onto the latest code and make the necessary changes to get things into a working state. I apologize for the long delay here and added work. 

If you need help please feel free to reach out. Cheers!

2021-04-23 18:40 UTC, SwampDragons commented
rebased and resolved conflicts.

2021-04-23 19:37 UTC, SwampDragons approved these changes

2021-04-23 23:53 UTC, SwampDragons commented
Pushed code to fix broken artifacts. Since this is an oft-requested feature, I'm merging even though the artifact isn't quite perfect. We can tweak once the Azure builder is split out, if we decide we want to.

2021-04-23 23:55 UTC, merged