Add 'create_image' option to googlecompute
hashicorp/packer pull request #10115
Opened 2020-10-15 22:06 UTC by bhundven

When building a CI/CD deployment, during the PR process it's nice to be
able to run the builder, but not create the image the build produces.

Closes #9965

2020-10-15 22:06 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10115)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10115)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10115).</sub>

2020-10-16 22:03 UTC, bhundven commented
@azr I tested this in our gitlab-ci pipeline, and this does exactly what I was looking for in #9965.

2020-10-16 22:11 UTC, SwampDragons requested changes
Hey, thanks for opening a PR! This looks great to me -- the only suggestion I have is that generally when we add these kinds of template options to skip a default step, we name it with the prefix skip_ -- so you'd call the option "skip_create_image", which would automatically default to false without you having to iterate over the metadata keys. Then, when true, it would skip the creation. Do you mind switching your feature to follow that convention?

2020-10-16 22:17 UTC, bhundven commented
> Hey, thanks for opening a PR! This looks great to me -- the only suggestion I have is that generally when we add these kinds of template options to skip a default step, we name it with the prefix skip_ -- so you'd call the option "skip_create_image", which would automatically default to false without you having to iterate over the metadata keys. Then, when true, it would skip the creation. Do you mind switching your feature to follow that convention?

Can do, let me get that going.

2020-10-16 22:45 UTC, bhundven commented
Updated PR, and also updated the branch with master. @SwampDragons, Thank you for the suggestion!

2020-10-16 22:58 UTC, SwampDragons approved these changes

2020-10-16 23:01 UTC, merged

2020-10-16 23:02 UTC, SwampDragons commented
Fast turnaround -- thanks for this contribution!