Feat (builder/oracle-oci): Allow filtering on base image
hashicorp/packer pull request #10116
Opened 2020-10-15 22:15 UTC by OblateSpheroid

This adds `base_image_filter` to the config, which, if used, calls `ListImages()` from the Oracle SDK. This allows the user to specify attributes of the image instead of `base_image_ocid`. Packer will use the the most recent image that meets all search criteria. If no image meets all search criteria, Packer returns an error. 

All fields much match exactly except `display_name_search`, which uses a regular expression to search images returned from `ListImages()` and returns the most recent one.

Additionally, I've done some reorganizing of steps to create `instanceDetails` to make the code more readable and flow more logically.

Closes #8915

2020-10-19 18:28 UTC, SwampDragons requested changes
Hi, thanks for this!  Looks really good. I think the only thing I'd like to see before merge is a couple of tests in builder/oracle/oci/config_test.go that check the Prepare() functionality.

2020-10-19 18:28 UTC, SwampDragons commented on builder/oracle/oci/driver_oci.go
> +	instanceDetails := core.LaunchInstanceDetails{
This is a nice improvement.

2020-10-20 03:39 UTC, OblateSpheroid commented
I added two tests:
 - ensure user can leave out `base_image_ocid` if `base_image_filter` is non-empty
 - ensure if `base_image_filter[shape]` is not specified, it defaults `shape`

2020-10-20 10:18 UTC, azr approved these changes
This LGTM

2020-10-20 21:41 UTC, SwampDragons approved these changes

2020-10-20 21:41 UTC, merged