Report the time of provisioners:
hashicorp/packer pull request #10125
Opened 2020-10-19 14:54 UTC by maxim-lobanov

This pull-request adds additional logging to the following provisioners:
- shell
- powershell
- windows-shell
- windows-restart

Additional logging includes the duration of every script that is run on machine. It improves visibility and allows to find bottlenecks (scripts that take too much time).

Example of output:
![image](https://user-images.githubusercontent.com/16715858/96467856-0e277b80-1234-11eb-98b2-a3796b641f81.png)

Closes #10072

2020-10-19 15:11 UTC, azr requested changes
Hello there, thanks for opening, nice one; I think the timing code should be in a `TimedProvisioner` struct. So that we don't have to duplicate/maintain this code for each and every provisioner.

Very similarly to the `DebuggedProvisioner`: https://github.com/hashicorp/packer/blob/3fb7ddf5095aff02cdf47220e17622de3ef1cb51/packer/provisioner.go#L219

We'd [wrap a provisioner](https://github.com/hashicorp/packer/blob/6d0b5a6957f201875214222e2122709f7ab204a7/packer/build.go#L249) when a [`-time-provisioners` option is set](https://github.com/hashicorp/packer/blob/6d0b5a6957f201875214222e2122709f7ab204a7/packer/build.go#L247).

Edit: yes about shell provisioner having multiple scripts, then I'd agree with adding that specific code only for those, 🤔

2020-10-19 15:24 UTC, maxim-lobanov commented on provisioner/powershell/provisioner.go
> +	"github.com/hako/durafmt"
We already use it in packer repo in some places :)

2020-10-19 15:35 UTC, maxim-lobanov commented
> Hello there, thanks for opening, nice one; I think the timing code should be in a `TimedProvisioner` struct. So that we don't have to duplicate/maintain this code for each and every provisioner.
> 
> Very similarly to the `DebuggedProvisioner`:
> 
> https://github.com/hashicorp/packer/blob/3fb7ddf5095aff02cdf47220e17622de3ef1cb51/packer/provisioner.go#L219
> 
> We'd [wrap a provisioner](https://github.com/hashicorp/packer/blob/6d0b5a6957f201875214222e2122709f7ab204a7/packer/build.go#L249) when a [`-time-provisioners` option is set](https://github.com/hashicorp/packer/blob/6d0b5a6957f201875214222e2122709f7ab204a7/packer/build.go#L247).
> 
> Edit: yes about shell provisioner having multiple scripts, then I'd agree with adding that specific code only for those, 🤔

Yes, I thought about some place where this logic can be unified but failed. I don't think that it makes sense to log the time of every provisioner in total because you can run multiple scripts in provisioner. See example in our code: https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu1804.json#L149

So we definitely should log it into provisioners but please advice if you see better options

2020-10-19 16:44 UTC, SwampDragons commented
I think the right answer is both, to be honest -- we can have a whole-provisioner timer, and a per-script timer inside the various shell provisioners.

2020-10-20 10:02 UTC, azr commented
> I think the right answer is both, to be honest
Yes I agree,  that's what I was trying to say in my edit message, sorry it was unclear. 🙂

2020-10-20 17:13 UTC, maxim-lobanov commented
@SwampDragons , @azr thank you for feedback. Probably, it will take some time to rework. Will take a look on weekend

2021-02-18 10:44 UTC, sylviamoss commented
Hello @maxim-lobanov, are you still planning to work on this?

2021-02-18 11:33 UTC, maxim-lobanov commented
Nope, closing the PR.
I have achieved the same goal via https://github.com/hashicorp/packer/issues/10072#issuecomment-735407403

2021-02-18 11:33 UTC, closed without merging