Add qemu chroot builder
hashicorp/packer pull request #10269
Opened 2020-11-17 02:14 UTC by wangzw

Implement qemu chroot builder

This build take a qcow2 format image as input, convert it to raw format and mount to host directory and setup chroot communicator. After provision work, unmount raw image and convert it to a new qcow2 image.

2020-11-17 02:14 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10269)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10269)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10269).</sub>

2020-12-18 22:06 UTC, SwampDragons requested changes
Wow, this is a really wonderful contribution!  I've got a couple notes inline, and some broader questions and comments I'll share here. 

- It looks like you've generated the "partials" documentation that we build from structs, which is a great start -- but you still need to create the web page too. You can look at how the qemu-iso page is built as an example

- Apart from the qemu-img convert command, it looks like this doesn't actually use qemu or kvm anywhere, and that the chroot build doesn't require a hypervisor. Since that's the case, I wonder if it really makes sense to call it a "qemu-chroot" build. I think it would be great to generalize it. We could name it "localhost-chroot" build or something like that, and provide a configurable option for image conversion, setting the qemu-img call as the default. 

- You're making this plugin contribution right as the Packer team at HashiCorp is spending all of our engineering effort on preparing to split plugins _out_ of Packer. This provides us with a really wonderful opportunity; rather than merging this plugin with the Packer core, I think it would be amazing if we could keep this in your repo and then have the Packer team work together with you to get you set up serve your plugin as a standalone plugin, registered with HashiCorp and available for users to pull and download as they desire. Would you be willing to work with us on that?  (note -- it's the holiday season and most of the Packer team is going to be away from their computers for the next two weeks, so this would be something that we would start working on in January)

Thank you so much for this! People have been requesting a chroot builder for a long time and this represents a lot of work and a lot of understanding of the Packer internals to make this happen.

2021-01-17 13:06 UTC, wangzw commented on builder/qemu/chroot/builder.go
> +	// in the Chroot Mounts section. Please read that section for more
So, what should I do? I clone this plugin from amazon chroot plugin and modify some comments. I have no clue how the document generated.

2021-01-17 13:19 UTC, wangzw commented on builder/qemu/chroot/step_attach_device.go
> +	time.Sleep(5 * time.Second)
I was trying to find a better way, but not find an easy way to do that. From the man page, the sleep is not necessary but I adding it just in case.

2021-01-17 13:53 UTC, wangzw commented
> Wow, this is a really wonderful contribution! Thanks for your patience in waiting for a review. I've got a couple notes inline, and some broader questions and comments I'll share here.
> 
> * It looks like you've generated the "partials" documentation that we build from structs, which is a great start -- but you still need to create the web page too. You can look at how the qemu-iso page is built as an example

Let me figure out how to add it

> * Apart from the qemu-img convert command, it looks like this doesn't actually use qemu or kvm anywhere, and that the chroot build doesn't require a hypervisor. Since that's the case, I wonder if it really makes sense to call it a "qemu-chroot" build. I think it would be great to generalize it. We could name it "localhost-chroot" build or something like that, and provide a configurable option for image conversion, setting the qemu-img call as the default.

My original purpose of this plugin is to create an image for qemu and it use qemu-img. It's cool to generalize it, but I think it is another story and needs some use case too. I'd like to keep an issue simple and small.

> * You're making this plugin contribution right as the Packer team at HashiCorp is spending all of our engineering effort on preparing to split plugins _out_ of Packer. This provides us with a really wonderful opportunity; rather than merging this plugin with the Packer core, I think it would be amazing if we could keep this in your repo and then have the Packer team work together with you to get you set up serve your plugin as a standalone plugin, registered with HashiCorp and available for users to pull and download as they desire. Would you be willing to work with us on that?  (note -- it's the holiday season and most of the Packer team is going to be away from their computers for the next two weeks, so this would be something that we would start working on in January)

In my opinion keeping common and widely used builders with Packer make user happy. And a good plugin marketplace is also a great idea.

Where can I register with HashiCorp and deploy my plugin? I'm trying google but not found. 

I like the way of using plugin of vagrant, just one command and then it is ready to use. So it's good to me if packer plugin can do like that.

> 
> Thank you so much for this! People have been requesting a chroot builder for a long time and this represents a lot of work and a lot of understanding of the Packer internals to make this happen.

2021-01-19 19:10 UTC, SwampDragons commented
> Where can I register with HashiCorp and deploy my plugin? I'm trying google but not found.
We're still building the initialization process. For now, it will involve releasing the plugin on github, and allowing users to declare their plugin in a special new required_plugins block. That work should be merged this week, and once it is in place we can work with you to get your plugin set up to use it

> I like the way of using plugin of vagrant, just one command and then it is ready to use. So it's good to me if packer plugin can do like that.
We're writing a "packer init" command right now that will allow this. For now, you should follow the instructions [here](https://www.packer.io/docs/extending/plugins) to learn how to turn this PR into a standalone plugin rather than one stored inside the Packer code base.

2021-02-19 23:51 UTC, SwampDragons commented
We've released "packer init" and the relevant plugin information. 

All information on developing plugins can be found starting here: https://www.packer.io/docs/plugins/creation

You may want to skip down to https://www.packer.io/docs/plugins/creation#creating-a-github-release

I'm going to close this and let you create a standalone plugin using those instructions. Then, when you're ready, we can document it on our website [here](https://www.packer.io/docs/builders/community-supported) so we can direct users about where to find it.

2021-02-19 23:51 UTC, closed without merging