Rename docs sidebar from From v1.5 to HCL2
hashicorp/packer pull request #10481
Opened 2021-01-14 12:52 UTC by sylviamoss

The sidebar name with a version is becoming out of context as we make HCL2 our main configuration language. This PR updates not only the sidebar title but also the folder in the code.

2021-01-14 14:22 UTC, nywilken commented
> The reason for that is because we have some tests depending on this navigation and our markdown lint check can't validate the hcl2 links because they don't exist yet, the e5636ba commit is proof of that.

Yeah, these are the false positives I observed with the markdown checker. Seeing as this is meant to be a rename and breaking change I think it is okay to rename it to what it needs to be. The checker will fail but we can deploy theses changes to packer.io as these are not new documentation pages. 

An alternative would be to temporarily ignore the new links with the comment 

```
<!-- markdown-link-check-disable --> 
/new/link/page.mdx
<!-- markdown-link-check-enable -->
```

2021-01-14 14:23 UTC, nywilken approved these changes
LGTM - see comment about ignoring the mark link check for this PR.

2021-01-14 14:53 UTC, azr requested changes
This change looks super good to me, yeah, it's about time. 🙂 
I just think we need to make sure that links from the past do redirect correctly to the new URLs, I think https://github.com/hashicorp/packer/blob/master/website/redirects.next.js does that !

Cheers !

2021-01-14 14:55 UTC, azr commented
[Pinging @jescalan just in case]

2021-01-14 15:04 UTC, sylviamoss commented
> I just think we need to make sure that links from the past do redirect correctly to the new URLs, I think https://github.com/hashicorp/packer/blob/master/website/redirects.next.js does that !

I believe the redirects will still work because the page still exists, the only thing I've changed was the sidebar that now is pointing to the new hcl2 folder that has the same content as before. Once we remove the from-v1.5 folder we will then break all of those redirects and need to fix them to point to hcl2. I think we should update them when we remove from-v1.5

2021-01-14 15:11 UTC, sylviamoss commented
> Yeah, these are the false positives I observed with the markdown checker. Seeing as this is meant to be a rename and breaking change I think it is okay to rename it to what it needs to be. 

I will commit the changes then. If we change our mind I can just reset that commit.

2021-01-14 15:14 UTC, azr commented
ah got it, yes that makes sense ! I would have moved everything out of 1.5 and then fix the tests :), your call !

2021-01-14 15:22 UTC, sylviamoss commented on website/redirects.next.js
> +    destination: '/docs/hcl2/:path*',
Added these two redirects from the old paths to the new ones.

2021-01-14 15:34 UTC, sylviamoss commented on website/redirects.next.js
> +    source: '/docs/from-1.5/:path*',
Added this new redirect

2021-01-14 22:20 UTC, SwampDragons commented
Oh no I started on something similar last night and just opened a Pr too 🤦

2021-01-15 09:56 UTC, sylviamoss commented
I'm closing this one because https://github.com/hashicorp/packer/pull/10486 does the same and more.

2021-01-15 09:56 UTC, closed without merging