Update Config-not-required.mdx
hashicorp/packer pull request #10527
Opened 2021-01-26 18:48 UTC by dreic

Found a bug in extra_arguments format that doesn't match ansible documentation and need clarification.

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

In order to have a good experience with our community, we recommend that you
read the contributing guidelines for making a PR, and understand the lifecycle
of a Packer PR:

https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md#opening-an-pull-request

Describe the change you are making here!

Please include tests. Check out these examples:

- https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/ssh_config_test.go#L19-L37
- https://github.com/hashicorp/packer/blob/master/post-processor/compress/post-processor_test.go#L153-L182

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #xxx
Closes #xxx

2021-01-26 18:48 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10527)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10527)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10527).</sub>

2021-01-26 23:07 UTC, SwampDragons requested changes
Hi, thanks for your contribution!  This looks like a good comment to add, but you need to do so in the struct comments here https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L58 because the file you've modified is automatically generated from those comments.

2021-02-18 10:40 UTC, sylviamoss commented
I pushed the fix for this one.

2021-02-18 10:46 UTC, sylviamoss approved these changes

2021-02-18 10:47 UTC, merged