Support both role and collection installation in ansible-local provisioner
hashicorp/packer pull request #10667
Opened 2021-02-19 21:36 UTC by emansom

Ansible Galaxy skips installation of collections when invoked with `-p`. Described in [this](https://github.com/ansible/ansible/pull/67843#issuecomment-629572885) upstream Ansible issue comment.
See [following bug report](https://github.com/hashicorp/packer/issues/10666) for further discussion.

2021-02-19 21:36 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10667)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10667)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10667).</sub>

2021-02-19 21:59 UTC, emansom commented
@JoakimLofgren Spiting through `git` history; you seem to have introduced this functionality. Does removal of `-p` in lieu of upstream (being Ansible) favoring global role installation locations work with your workflow?

If not, do you see a way to support both usecases? Overriding role path as well as conforming to Ansible desires?

2021-02-19 22:09 UTC, emansom commented
@jborean93 Would this be a invocation of Ansible Galaxy that would result in all usecases being met? What if someone wants to install roles to a different directory while using collections as well?

2021-02-25 22:20 UTC, JoakimLofgren commented
@emansom The `-p` flag was used to load additional roles checked in to the repo.

2021-02-27 04:29 UTC, emansom commented
> @emansom The `-p` flag was used to load additional roles checked in to the repo.

Following @jborean93's table on Ansible Galaxy CLI's install behavior [here](https://github.com/ansible/ansible/pull/67843#issuecomment-629572885), that'll counterintuitively keep Ansible Collections from being installed.
Resulting in following [error output](https://gist.github.com/emansom/61cd34555b96dda6230e32d962d66e1a#file-packer-output-txt-L403-L412) when using [this](https://gist.github.com/emansom/61cd34555b96dda6230e32d962d66e1a#file-requirements-yml) Ansible Galaxy file.

Current Ansible Galaxy CLI behavior is to enforce and prefer system wide location paths for both roles and collections.

The Ansible ecosystem has [moved towards easy reusability](https://www.jeffgeerling.com/blog/2020/collections-signal-major-shift-ansible-ecosystem), relying on Ansible Collections throughout more and more; it makes sense to make Packer reflect this change.
To not suprise current users however; we should remain compatible with current behavior.

The logic this PR proposes is to first execute the role install to custom path, then execute the global install which installs both roles and collections to system wide paths.
https://github.com/hashicorp/packer/blob/b284b1981935f7b82aeeb162973dba89827c3df4/provisioner/ansible-local/provisioner.go#L410-L418
https://github.com/hashicorp/packer/blob/b284b1981935f7b82aeeb162973dba89827c3df4/provisioner/ansible-local/provisioner.go#L379-L399
https://github.com/hashicorp/packer/blob/b284b1981935f7b82aeeb162973dba89827c3df4/provisioner/ansible-local/provisioner.go#L358-L377

This way Packer remains backwards compatible, while embracing the new standard system wide Ansible Galaxy role and collection paths.
That's the theory. Testers needed!

Could you test if this code path works the way you intended Ansible Galaxy roles to be utilized?
Prepped the following [test build](https://github.com/emansom/packer/releases/tag/1.7.1-dev) for easy testing in my fork [here](https://github.com/emansom/packer/releases/tag/1.7.1-dev).

2021-03-09 00:13 UTC, SwampDragons commented
Thanks for opening this PR, and sorry for the delay in reviewing. 

This is a situation where we've seen some configuration drift between the ansible-local and ansible (remote) provisioners. I feel like it might make the most sense to take a page from the ansible (remote) provisioner and add a CollectionsPath field to the config struct, and then install roles and collections totally independently. Here's the logic in the ansible provisioner: https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L634-L680

Looking at the logic you describe above, I _think_ this means that we'd see the same behavior for a user who only sets RolesPath as they currently get with the -p flag anyway.  Thoughts?

2021-03-09 00:19 UTC, SwampDragons requested changes
See the comment I threw inline. I think this is on the right track, but while you're at it it'd be better to just bring this directly back into line with the ansible remote provisioner.

2021-03-10 21:55 UTC, gamethis commented
if the goal is backward compatibility and you are separating out role from collection install... I think you should add `collection` in the command line for collection. and call out that you are doing collection installs.

otherwise with the newer version your ansible-galaxy install will catch roles and collections in one go. doing roles twice could throw some errors for you on the second go.

2021-03-17 11:46 UTC, wilsonge commented
@SwampDragons can you take a look at https://github.com/hashicorp/packer/pull/10768 - tried to address your comments there

2021-04-26 20:24 UTC, SwampDragons commented
Closing this, since the Ansible plugin has been extracted to its own repo. We've ported the desired changes over to https://github.com/hashicorp/packer-plugin-ansible/pull/38

2021-04-26 20:24 UTC, closed without merging