Support for ansible collections in local ansible provisioner
hashicorp/packer pull request #10768
Opened 2021-03-16 15:50 UTC by wilsonge

https://github.com/hashicorp/packer/issues/10666
Alternative to https://github.com/hashicorp/packer/pull/10667

Sorry I'm not a go developer (I usually sit in Python/PHP langs :) ) and not been able to get the project running locally (I think because brew is still installing go 1.15.7 and I believe you guys are using 1.16+). If you guys have any advice happy to take it on so I can run any fmt and tests :) 

But this reuses some code from the ansible provisioned to use collections from ansible galaxy. It addresses some of the comments in #10667.

2021-03-16 15:50 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10768)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=10768)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=10768).</sub>

2021-03-16 17:18 UTC, wilsonge commented
So I think this will upload and run the correct commands. However it's not going to find the uploaded roles/collections from galaxy. The previous version of the code dropped them into the roles folder being uploaded from the local vm. but i guess this can end up with local files being overwritten by galaxy files. I think it's better to drop them into the local directory and load them with ansible as an extra directory. https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-roles-path and https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths should do the trick for this. But I'm unsure how to set this in your packer cmd context compared to the stackoverflow answer here https://stackoverflow.com/questions/41133115/pass-env-var-to-exec-command

2021-03-17 00:31 UTC, wilsonge commented
OK Well it's probably not the prettiest code ever. But I think this is functional and ready to review at least with my basic testing.

2021-03-23 17:45 UTC, SwampDragons requested changes
The code overall looks fine-- thanks for addressing my comments on the other PR. My main concern now is that moving forward we'll still have the same root problem, which is unnecessary configuration drift between the two provisioners. 

It would be cool to extract the command generation code into a common function that can be used by either provisioner. I think the best way to do this would be to add a new directory "github.com/hashicorp/provisioner/ansible/common" and extract and generalize the "executeGalaxy" function from each provisioner into that folder. 

In golang we can use inheritance to reuse sub-sets of our configuration structure. For example, we can create a new galaxy config that lives in our new "common" directory:

```golang
type GalaxyConfig struct {
	GalaxyFile string `mapstructure:"galaxy_file"`
	// The command to invoke ansible-galaxy. By default, this is
	// `ansible-galaxy`.
	GalaxyCommand string `mapstructure:"galaxy_command"`
	// Force overwriting an existing role.
	//  Adds `--force` option to `ansible-galaxy` command. By default, this is
	//  `false`.
	GalaxyForceInstall bool `mapstructure:"galaxy_force_install"`
	// The path to the directory on your local system in which to
	//   install the roles. Adds `--roles-path /path/to/your/roles` to
	//   `ansible-galaxy` command. By default, this is empty, and thus `--roles-path`
	//   option is not added to the command.
	RolesPath string `mapstructure:"roles_path"`
	// The path to the directory on your local system in which to
	//   install the collections. Adds `--collections-path /path/to/your/collections` to
	//   `ansible-galaxy` command. By default, this is empty, and thus `--collections-path`
	//   option is not added to the command.
	CollectionsPath string `mapstructure:"collections_path"`
}
```

Then embed it in the main Config struct of each provisioner (ansible and ansible-local) using

```golang
import (
	...

	ansiblecommon "github.com/hashicorp/provisioner/ansible/common"
)

type Config struct {
	common.PackerConfig `mapstructure:",squash"`
	ctx                 interpolate.Context

	...blahblah all the other config options
	
	ansiblecommon.GalaxyConfig `mapstructure:",squash"`
}
```
	
... and removing all of the fields that we pulled into the GalaxyConfig from the "parent" struct (I'm using Parent cause you have a Python history, but this isn't inheritance and thinking about it that way will get you in trouble).

As you probably just guessed, PackerConfig is also a separate struct that we embed in basically all our plugins. 

Where the defaulting is the same, you can even reuse the defaulting code by creating a Prepare() method on that GalaxyConfig and then calling the GalaxyConfig.Prepare() from inside the Prepare() method of the main Config.

Let me know if you have issues implementing this or if anything I've said isn't clear to you. I am happy to push up a refactor to your branch if you need a hand, but I figure I'll let you have at it if you'd prefer. 

Anyway, this definitely also needs docs for the new options added to https://github.com/hashicorp/packer/blob/master/website/content/docs/provisioners/ansible-local.mdx; Most of our provisioners auto-generate docs based on struct tags, but this one doesn't yet and it feels out of scope to ask you to implement that generation. I'll make a ticket to update the code generation somewhere else.

Finally, I'd really love to see tests for the executeGalaxy function once you've extracted it. Take a look at the file named provisioner_test.go in the ansible and/or ansible-local directories to get an idea for how to structure tests in golang, and if you get stuck ping me.

2021-03-25 01:06 UTC, wilsonge commented
Docs uploaded. Will try and figure my way through the refactoring you proposed (is it really logical that the ansible module has the common code for the ansible-local provisioner?) - surely if it's going to be shared it should be in some other directory that isn't specific to either of the provisioners causing hard deps between the provisioners (understand that's kinda an implementation detail and can press on for now without an immediate answer).

Thanks for the layman terms explanations in python btw. Super appreciated!

2021-03-29 17:23 UTC, SwampDragons commented
>is it really logical that the ansible module has the common code for the ansible-local provisioner?

You're right that it isn't ideal; there should be a higher level "common" directory that they both reference, but that's not how the Packer code is laid out, and said higher level code is undergoing a lot of refactoring at the moment so it's safer to keep the directory internal to one of the provisioners for now. Having hard dependencies between the provisioners isn't a "real" problem since they always ship together. The Packer team is in the process of splitting plugins out of the core, and when that happens would be a good time to make a common directory that they both reference, since both ansible components will live in the same plugin. I suggested putting the "common" directory inside the "ansible" plugin folder because eventually the directory structure of the standalone plugin will look like: 

```
packer-plugin-ansible // repo name
|_ ansible-local // referenced as ansible-local in packer template configs
|_ ansible-remote // referenced as ansible in packer template configs
|_common
```

But for now, sticking "common" inside the ansible subdirectory will keep it scoped in a nearly-logical way that will prevent other stuff from accidentally getting tossed into an ansible-specific common folder.

2021-04-22 10:45 UTC, aslafy-z commented on website/content/docs/provisioners/ansible-local.mdx
> +- `galax_roles_path` (string) - The path to the directory on the remote system in which to
```suggestion
- `galaxy_roles_path` (string) - The path to the directory on the remote system in which to
```

2021-04-22 17:48 UTC, SwampDragons commented
Oh shoot, the new ansible plugin repo got extracted out from under this PR. I'll migrate the PR when I have a chance.

2021-04-22 19:13 UTC, nywilken commented
@SwampDragons @wilsonge the changes in this PR were ported over to the packer-plugin-ansible repo https://github.com/hashicorp/packer-plugin-ansible/pull/38

We will work on making the final requested changes to get the feature merged. Thanks for the contribution @wilsonge

2021-04-22 19:13 UTC, closed without merging