Add tip about using local instead of locals for complex cases
hashicorp/packer pull request #11036
Opened 2021-05-20 12:43 UTC by sylviamoss

As a result of https://github.com/hashicorp/packer/issues/10981 we would like to have that tip on our docs.

2021-05-21 22:35 UTC, SwampDragons requested changes
Small grammar nitpicks, but I'm glad you wrote this!

2021-05-21 22:35 UTC, SwampDragons commented on website/content/docs/templates/hcl_templates/locals.mdx
> +This block is also very useful to define complex locals. Packer might take some time to expands and evaluate `locals`
```suggestion
This block is also very useful for defining complex locals. Packer might take some time to expand and evaluate `locals`
```

2021-05-21 22:35 UTC, SwampDragons commented on website/content/docs/templates/hcl_templates/locals.mdx
> +with complex expressions dependent on other locals. The `locals` block is read as map and maps are not sorted,
```suggestion
with complex expressions dependent on other locals. The `locals` block is read as a map.  Maps are not sorted, and therefore
```

2021-05-21 22:35 UTC, SwampDragons commented on website/content/docs/templates/hcl_templates/locals.mdx
> +To avoid that, singular `local` block should be used instead. These will be
```suggestion
To avoid that, singular `local` blocks should be used instead. These will be
```

2021-05-25 01:42 UTC, nywilken commented on website/content/docs/templates/hcl_templates/locals.mdx
> +and the evaluation time is not deterministic.
```suggestion
the evaluation time is not deterministic.
```

2021-05-25 01:49 UTC, nywilken approved these changes
I've addressed all of @SwampDragons suggestions. This updates looks great!

2021-05-25 01:50 UTC, merged

2021-05-25 07:23 UTC, sylviamoss commented
Thank you @nywilken! You're great 😄