Create parent directories for packer log path if they don't exist
hashicorp/packer pull request #11539
Opened 2022-01-29 01:13 UTC by abhay-krishna

This PR adds the logic to handle the packer log parent directory creation.

2022-01-29 01:13 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=11539)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=11539)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=11539).</sub>

2022-02-01 05:38 UTC, abhay-krishna commented
Could I get a review here please? Thanks!

2022-02-01 06:37 UTC, ChiefGhostZero0x1 approved these changes
/approve.  I'm a bit concerned since I am not 100% but without trust there is no progress.  Can you please send me a copy of your findings so I can better see... Thank you!

2022-02-02 16:27 UTC, nywilken requested changes
Hi @abhay-krishna thanks for opening up this change sorry we couldn't get back to you quickly. I can see why you would want this logic but ultimately it is not something we want to handle in Packer. The thought process here is that if Packer creates the directory it should report to the user what was created and possibly have a way for removing the directories if requested. 

Instead we encourage the user to manage the creation of any logging or debugging directories directly. Since this is usually a pretty straight forward operation that can be performed before running a build I'm going to close this PR.

2022-02-02 16:28 UTC, closed without merging

2022-02-15 05:00 UTC, ChiefGhostZero0x1 commented
/open