Improve clarity
hashicorp/packer pull request #11798
Opened 2022-05-22 13:12 UTC by 3point2

It's not clear what template_file referred to.

2022-05-22 13:12 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=11798)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=11798)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=11798).</sub>

2022-05-23 19:54 UTC, nywilken requested changes
Hi @3point2 thanks for opening up this PR. The documentation for the builders are generated from the comments. Since you updated the comment could you run `make generate` to update the generated comments with you change please.

2022-05-28 19:49 UTC, 3point2 commented
Done, thanks for the tip!

2022-05-30 09:01 UTC, sylviamoss approved these changes

2022-05-31 14:08 UTC, nywilken approved these changes
Thank you!

2022-05-31 14:10 UTC, merged