feat: support pwsh in powershell provisioner
hashicorp/packer pull request #11841
Opened 2022-06-10 14:29 UTC by edeustace

* set `pwsh` to true in config to run `pwsh.exe`, default is false.
* add docs

Closes #7164

2022-06-10 14:29 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=11841)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=11841)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=11841).</sub>

2022-07-29 13:36 UTC, lbajolet-hashicorp approved these changes
Just a nit regarding a condition in the test, outside of that LGTM!

Thanks for the contribution, and sorry for the late review

2022-08-12 19:46 UTC, lbajolet-hashicorp requested changes
Coming back on this PR, after a re-reading of the code, we think it'd be beneficial to address a few remaining comments before we can merge this, any chance you can address those @edeustace?

2022-08-12 19:46 UTC, lbajolet-hashicorp commented on provisioner/powershell/provisioner.go
> +	  return fmt.Sprintf(`powershell -executionpolicy %s "%s"`, p.config.ExecutionPolicy, baseCmd)
Re-reading through this PR, I notice the indentation is off here, could you replace the two-spaces by a tab? That'd help it stay consistent with the rest of the code and the Go guidelines.

2022-08-12 19:46 UTC, lbajolet-hashicorp commented on provisioner/powershell/provisioner.go
> +	Pwsh bool `mapstructure:"pwsh"`
As noted by @JenGoldstrich in a out-of-band discussion, `UsePwsh` would be a clearer name for the attribute, could you amend this?

2022-08-19 18:01 UTC, nywilken commented
HI @edeustace thanks for the contribution. I'm going to close this PR as your changes, along with commit history, have been rolled into #11950. The team requested a few changes a bit late so we thought it best to make the changes along with yours in a separate PR. Thanks again for making the fix. 

We look forward to the continued contributions and feedback. Cheers!

2022-08-19 18:01 UTC, closed without merging

2022-09-07 19:55 UTC, edeustace commented
Sorry - I was on vacation - thanks!