website: Added Tart builder
hashicorp/packer pull request #12126
Opened 2022-11-24 01:10 UTC by fkorotkov

This PR add [`tart` builder](https://github.com/cirruslabs/packer-plugin-tart) to the list of all the builders.

Tart is a open-source toolset for building, running and managing Linux and macOS virtual machines on Apple Silicon. Part of the toolset is this packer plugin.

2022-11-24 01:10 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer?pullRequest=12126)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer?pullRequest=12126)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer?pullRequest=12126).</sub>

2022-12-12 18:11 UTC, nywilken requested changes
Hi @fkorotkov thanks for opening up this change, and for adding to the Packer ecosystem. Taking a look at the available docs for the Tart plugin https://packer-zp11kekqt-hashicorp.vercel.app/packer/plugins/builders/tart I think the plugin would benefit from some additional content on "What is Tart?" and "How to get started with Tart". 

Taking a quick look at the [Tart README](https://github.com/cirruslabs/tart) I see some details on the project and how to install that you be nice to summarize on the plugin docs, along with a link back to the Tart documentation.

2022-12-12 19:32 UTC, fkorotkov commented
My bad @nywilken! I though `README.md` from `docs` will be picked up for some reason. In any case it was still not quite good so I've improved the documentation in https://github.com/cirruslabs/packer-plugin-tart/pull/39 which got published as part of `v0.6.1` release.

2022-12-12 19:35 UTC, fkorotkov commented
Rebased my branch to invalidate the review. PTAL.

2022-12-12 20:08 UTC, nywilken approved these changes
@fkorotkov all good here. Thank you for the quick response on the PR; apologies for not being able to get to it sooner. 
The updated docs looks great https://packer-flvzgd52s-hashicorp.vercel.app/packer/plugins/builders/tart

2022-12-12 20:13 UTC, nywilken commented
>  I though README.md from docs will be picked up for some reason. 

Sorry for the confusion here. The current remote-docs setup only looks for files within the following directories
```
docs/
  builders/*
  datasources/*
  provisioiners/*
  postprocessors/*
```
Anything outside of that is ignored. In the future if you want to include an overview file for one of the component types like we do for [Amazon builders](https://packer-flvzgd52s-hashicorp.vercel.app/packer/plugins/datasources/amazon) you could drop a `index.mdx` file in component directory and it will act as the main index for the said component types.

2022-12-12 20:13 UTC, merged