github: only publish latest release images
hashicorp/packer pull request #12913
Opened 2024-04-09 20:27 UTC by lbajolet-hashicorp

When building the container images for Packer (light and full), we should only publish them in the version being built is a release, and not a pre-release.

Changing this means that both light and full latest will always be only a final release at any time.

2024-04-11 00:26 UTC, dekimsey requested changes
Hi Lucas, looks like I gave you bad advice 😞 . I forgot GHA Expressions must use single quotes (`'`).

I created a bunch of suggestions to make it easy to apply.

To test the PR I triggered a workflow dispatch on your branch and this [run](https://github.com/hashicorp/packer/actions/runs/8639545983) came of it. It errored immediately with a syntax error:

> The workflow is not valid. .github/workflows/build.yml (Line: 244, Col: 17): Unexpected symbol: '""'. Located at position 64 within expression: steps.get-product-version.output.prerelease-product-version == "" && format("docker.io/hashicorp/{0}:light", env.REPO_NAME) .github/workflows/build.yml (Line: 274, Col: 17): Unexpected symbol: '""'. Located at position 64 within expression: steps.get-product-version.output.prerelease-product-version == "" && format("docker.io/hashicorp/{0}:full", env.REPO_NAME)

2024-04-11 00:26 UTC, dekimsey commented on .github/workflows/build.yml
> +            ${{ steps.get-product-version.output.prerelease-product-version == "" && format("docker.io/hashicorp/{0}:light", env.REPO_NAME) }}
```suggestion
            ${{ steps.get-product-version.output.prerelease-product-version == '' && format('docker.io/hashicorp/{0}:light', env.REPO_NAME) }}
```

One day I'll remember to use single quotes in GHA templates

2024-04-11 00:26 UTC, dekimsey commented on .github/workflows/build.yml
> +            ${{ steps.get-product-version.output.prerelease-product-version == "" && format("public.ecr.aws/hashicorp/{0}:light", env.REPO_NAME) }}
```suggestion
            ${{ steps.get-product-version.output.prerelease-product-version == '' && format('public.ecr.aws/hashicorp/{0}:light', env.REPO_NAME) }}
```

2024-04-11 00:26 UTC, dekimsey commented on .github/workflows/build.yml
> +            ${{ steps.get-product-version.output.prerelease-product-version == "" && format("docker.io/hashicorp/{0}:full", env.REPO_NAME) }}
```suggestion
            ${{ steps.get-product-version.output.prerelease-product-version == '' && format('docker.io/hashicorp/{0}:full', env.REPO_NAME) }}
```

2024-04-11 00:26 UTC, dekimsey commented on .github/workflows/build.yml
> +            ${{ steps.get-product-version.output.prerelease-product-version == "" && format("public.ecr.aws/hashicorp/{0}:full", env.REPO_NAME) }}
```suggestion
            ${{ steps.get-product-version.output.prerelease-product-version == '' && format('public.ecr.aws/hashicorp/{0}:full', env.REPO_NAME) }}
```

2024-04-11 15:01 UTC, nywilken approved these changes
Looks like all of @dekimsey suggestions were addressed. This looks good to me 👍🏽

2024-04-11 15:06 UTC, lbajolet-hashicorp commented
Marking as draft temporarily so we don't merge it too early, as light/full are still pushed as latest due to prerelease-version always being empty

2024-04-11 21:23 UTC, nywilken commented
> Marking as draft temporarily so we don't merge it too early, as light/full are still pushed as latest due to prerelease-version always being empty

As discussed pre-release should be set as expected. But is there a way to test this using artifactory and action logs to verify the behavior?

2024-04-16 14:10 UTC, nywilken approved these changes
:shipit:

2024-04-16 14:13 UTC, merged